[package]
name = "agentforge-storage-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
agentforge-application = { path = "../application" }
agentforge-domain = { path = "../domain" }

[lints]
workspace = true

